modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"
showAsResourcePack = false

[[mods]]
modId = "entity_pin_cushions"
version = "${version}"
displayName = "Entity Pin Cushions"
authors = "Traben"
description = '''
Lets arrows stick into most mobs, not just players.
'''
logoFile = "icon.png"

[[dependencies.entity_pin_cushions]]
modId = "forge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.entity_pin_cushions]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "CLIENT"


[[mixins]]
config = "entity_pin_cushions.mixins.json"
