modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "stuck_arrows_for_all"
version = "${version}"
displayName = "Stuck Arrows For All"
authors = "Traben"
description = '''
Lets arrows get stuck in most mobs, not just players.
'''
#logoFile = ""

[[dependencies.stuck_arrows_for_all]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stuck_arrows_for_all]]
modId = "minecraft"
type = "required"
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "stuck_arrows_for_all.mixins.json"
